import re
import os

migration_path = "packages/db/alembic/versions/58c05895d328_initial_schema.py"

with open(migration_path, "r") as f:
    content = f.read()

# Insert CREATE EXTENSION at the top of upgrade()
upgrade_idx = content.find("def upgrade() -> None:")
if upgrade_idx == -1:
    print("Could not find upgrade()")
    exit(1)

body_start = content.find("\n    # ### commands auto generated by Alembic - please adjust! ###", upgrade_idx)

extensions = """
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto;')
"""

content = content[:body_start] + extensions + content[body_start:]

# Find the end of the upgrade function commands
upgrade_end_idx = content.find("    # ### end Alembic commands ###", upgrade_idx)

tenant_tables = [
    "milos", "programs", "milestones", "tasks", "stakeholders", 
    "risks", "decisions", "commitments", "threads", "messages", 
    "tool_calls", "approvals", "agent_runs", "memory_chunks", 
    "memory_facts", "embeddings_jobs", "integrations", "oauth_tokens", 
    "integration_events", "subscriptions", "usage_meters", "invoices_cache"
]

rls_statements = ""
for table in tenant_tables:
    rls_statements += f"""
    op.execute("ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON {table} USING (tenant_id = current_setting('app.tenant_id')::uuid);")
    op.execute("ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
"""

content = content[:upgrade_end_idx] + rls_statements + content[upgrade_end_idx:]

with open(migration_path, "w") as f:
    f.write(content)

print("RLS injected successfully.")
