"""add_stakeholder_fields

Revision ID: 15e1022b808d
Revises: 41879a32321e
Create Date: 2026-05-10 18:31:55.692442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e1022b808d'
down_revision: Union[str, Sequence[str], None] = '41879a32321e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_stakeholders', sa.Column('email', sa.String(), nullable=True))
    op.add_column('program_stakeholders', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_stakeholders', 'last_active_at')
    op.drop_column('program_stakeholders', 'email')
    # ### end Alembic commands ###
