"""add_integration_config_to_tenants

Revision ID: 41879a32321e
Revises: 70da15cd4b2f
Create Date: 2026-05-10 17:50:24.453692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41879a32321e'
down_revision: Union[str, Sequence[str], None] = '70da15cd4b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stakeholders')
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('milos', 'hourly_monitor_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('tenants', sa.Column('integration_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'integration_config')
    op.alter_column('milos', 'hourly_monitor_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('stakeholders',
    sa.Column('work_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('influence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interest', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('satisfaction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_communication', sa.VARCHAR(), server_default=sa.text("'email'::character varying"), autoincrement=False, nullable=True),
    sa.CheckConstraint("influence::text = ANY (ARRAY['low'::character varying, 'med'::character varying, 'high'::character varying]::text[])", name=op.f('chk_sh_influence')),
    sa.CheckConstraint("interest::text = ANY (ARRAY['low'::character varying, 'med'::character varying, 'high'::character varying]::text[])", name=op.f('chk_sh_interest')),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('stakeholders_work_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('stakeholders_pkey'))
    )
    # ### end Alembic commands ###
